//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalScec.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlotYAxes {
            get {
                return ((int)(this["PlotYAxes"]));
            }
            set {
                this["PlotYAxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindowIsMaximized {
            get {
                return ((bool)(this["MainWindowIsMaximized"]));
            }
            set {
                this["MainWindowIsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double MainWindowLocationX {
            get {
                return ((double)(this["MainWindowLocationX"]));
            }
            set {
                this["MainWindowLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double MainWindowLocationY {
            get {
                return ((double)(this["MainWindowLocationY"]));
            }
            set {
                this["MainWindowLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainPlotWithErrors {
            get {
                return ((bool)(this["MainPlotWithErrors"]));
            }
            set {
                this["MainPlotWithErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MainPlotLineStyle {
            get {
                return ((int)(this["MainPlotLineStyle"]));
            }
            set {
                this["MainPlotLineStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MainPlotLineThickness {
            get {
                return ((int)(this["MainPlotLineThickness"]));
            }
            set {
                this["MainPlotLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double MainPlotDotThickness {
            get {
                return ((double)(this["MainPlotDotThickness"]));
            }
            set {
                this["MainPlotDotThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MainPlotMajorGridStyle {
            get {
                return ((int)(this["MainPlotMajorGridStyle"]));
            }
            set {
                this["MainPlotMajorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MainPlotMinorGridStyle {
            get {
                return ((int)(this["MainPlotMinorGridStyle"]));
            }
            set {
                this["MainPlotMinorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.338905")]
        public double FWHMU {
            get {
                return ((double)(this["FWHMU"]));
            }
            set {
                this["FWHMU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.001")]
        public double FWHMV {
            get {
                return ((double)(this["FWHMV"]));
            }
            set {
                this["FWHMV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001674")]
        public double FWHMW {
            get {
                return ((double)(this["FWHMW"]));
            }
            set {
                this["FWHMW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double HyperSensitivity {
            get {
                return ((double)(this["HyperSensitivity"]));
            }
            set {
                this["HyperSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double PeakMarkingThickness {
            get {
                return ((double)(this["PeakMarkingThickness"]));
            }
            set {
                this["PeakMarkingThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PeakMarkingStyle {
            get {
                return ((int)(this["PeakMarkingStyle"]));
            }
            set {
                this["PeakMarkingStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double AcceptedPeakBackgroundRatio {
            get {
                return ((double)(this["AcceptedPeakBackgroundRatio"]));
            }
            set {
                this["AcceptedPeakBackgroundRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int MaxHKLReflection {
            get {
                return ((int)(this["MaxHKLReflection"]));
            }
            set {
                this["MaxHKLReflection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.12619")]
        public double UsedWaveLength {
            get {
                return ((double)(this["UsedWaveLength"]));
            }
            set {
                this["UsedWaveLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double MaxMeasurmentAngle {
            get {
                return ((double)(this["MaxMeasurmentAngle"]));
            }
            set {
                this["MaxMeasurmentAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlotHKLOverview {
            get {
                return ((bool)(this["PlotHKLOverview"]));
            }
            set {
                this["PlotHKLOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double HKLAssociationRangeDeg {
            get {
                return ((double)(this["HKLAssociationRangeDeg"]));
            }
            set {
                this["HKLAssociationRangeDeg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PseudoVoigtRatio {
            get {
                return ((double)(this["PseudoVoigtRatio"]));
            }
            set {
                this["PseudoVoigtRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double FittingAngleConstraint {
            get {
                return ((double)(this["FittingAngleConstraint"]));
            }
            set {
                this["FittingAngleConstraint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double FittingSigmaConstraint {
            get {
                return ((double)(this["FittingSigmaConstraint"]));
            }
            set {
                this["FittingSigmaConstraint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.15")]
        public double FittingLorentzRatioConstraint {
            get {
                return ((double)(this["FittingLorentzRatioConstraint"]));
            }
            set {
                this["FittingLorentzRatioConstraint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MaxFittingTrials {
            get {
                return ((int)(this["MaxFittingTrials"]));
            }
            set {
                this["MaxFittingTrials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0001")]
        public double ParameterFittingAcuraccy {
            get {
                return ((double)(this["ParameterFittingAcuraccy"]));
            }
            set {
                this["ParameterFittingAcuraccy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public double FunctionFittingAcuraccy {
            get {
                return ((double)(this["FunctionFittingAcuraccy"]));
            }
            set {
                this["FunctionFittingAcuraccy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double FittingLambdaMulti {
            get {
                return ((double)(this["FittingLambdaMulti"]));
            }
            set {
                this["FittingLambdaMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double PeakWidthFWHM {
            get {
                return ((double)(this["PeakWidthFWHM"]));
            }
            set {
                this["PeakWidthFWHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FitWindowIsMaximized {
            get {
                return ((bool)(this["FitWindowIsMaximized"]));
            }
            set {
                this["FitWindowIsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double FitWindowHeight {
            get {
                return ((double)(this["FitWindowHeight"]));
            }
            set {
                this["FitWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1300")]
        public double FitWindowWidth {
            get {
                return ((double)(this["FitWindowWidth"]));
            }
            set {
                this["FitWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double FitWindowLocationX {
            get {
                return ((double)(this["FitWindowLocationX"]));
            }
            set {
                this["FitWindowLocationX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double FitWindowLocationY {
            get {
                return ((double)(this["FitWindowLocationY"]));
            }
            set {
                this["FitWindowLocationY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ResidualPlotMajorGridStyle {
            get {
                return ((int)(this["ResidualPlotMajorGridStyle"]));
            }
            set {
                this["ResidualPlotMajorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ResidualPlotMinorGridStyle {
            get {
                return ((int)(this["ResidualPlotMinorGridStyle"]));
            }
            set {
                this["ResidualPlotMinorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlotYFittingAxes {
            get {
                return ((int)(this["PlotYFittingAxes"]));
            }
            set {
                this["PlotYFittingAxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FittingPlotMajorGridStyle {
            get {
                return ((int)(this["FittingPlotMajorGridStyle"]));
            }
            set {
                this["FittingPlotMajorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FittingPlotMinorGridStyle {
            get {
                return ((int)(this["FittingPlotMinorGridStyle"]));
            }
            set {
                this["FittingPlotMinorGridStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.005")]
        public double FittingFunctionResolution {
            get {
                return ((double)(this["FittingFunctionResolution"]));
            }
            set {
                this["FittingFunctionResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticPeakFit {
            get {
                return ((bool)(this["AutomaticPeakFit"]));
            }
            set {
                this["AutomaticPeakFit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlotFittingOneSigmaLine {
            get {
                return ((bool)(this["PlotFittingOneSigmaLine"]));
            }
            set {
                this["PlotFittingOneSigmaLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlotFittingThreeSigmaLine {
            get {
                return ((bool)(this["PlotFittingThreeSigmaLine"]));
            }
            set {
                this["PlotFittingThreeSigmaLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double PatternLowerLimit {
            get {
                return ((double)(this["PatternLowerLimit"]));
            }
            set {
                this["PatternLowerLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public double PatternUpperLimit {
            get {
                return ((double)(this["PatternUpperLimit"]));
            }
            set {
                this["PatternUpperLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SampleVersion {
            get {
                return ((int)(this["SampleVersion"]));
            }
            set {
                this["SampleVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PatternVersion {
            get {
                return ((int)(this["PatternVersion"]));
            }
            set {
                this["PatternVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CODId {
            get {
                return ((int)(this["CODId"]));
            }
            set {
                this["CODId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PeakId {
            get {
                return ((int)(this["PeakId"]));
            }
            set {
                this["PeakId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReflexFitAutoCorrection {
            get {
                return ((bool)(this["ReflexFitAutoCorrection"]));
            }
            set {
                this["ReflexFitAutoCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double PsyAcceptanceAngle {
            get {
                return ((double)(this["PsyAcceptanceAngle"]));
            }
            set {
                this["PsyAcceptanceAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int REKAutoAusociationType {
            get {
                return ((int)(this["REKAutoAusociationType"]));
            }
            set {
                this["REKAutoAusociationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CubicFittingModel {
            get {
                return ((int)(this["CubicFittingModel"]));
            }
            set {
                this["CubicFittingModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RandomProbabilityIntervall {
            get {
                return ((double)(this["RandomProbabilityIntervall"]));
            }
            set {
                this["RandomProbabilityIntervall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UsedPeakDetectionId {
            get {
                return ((int)(this["UsedPeakDetectionId"]));
            }
            set {
                this["UsedPeakDetectionId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ODFSymmetricCalculation {
            get {
                return ((bool)(this["ODFSymmetricCalculation"]));
            }
            set {
                this["ODFSymmetricCalculation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextureTopologyCheck {
            get {
                return ((bool)(this["TextureTopologyCheck"]));
            }
            set {
                this["TextureTopologyCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActivateDECTextureWeighting {
            get {
                return ((bool)(this["ActivateDECTextureWeighting"]));
            }
            set {
                this["ActivateDECTextureWeighting"] = value;
            }
        }
    }
}
